version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tft-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/seed:/seed:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Optional: pgAdmin UI
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: tft-pgadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"

volumes:
  db_data: